spring:
  application:
    name: company-events
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL}
    open-in-view: true
  liquibase:
    change-log: classpath:db/company-events-changelog.xml
  config:
    import: "classpath:messages/messages.yml"


server:
  port: 3005
  address: 0.0.0.0
  forward-headers-strategy: native
  ssl:
    enabled: true
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: "changeit"
    key-store-type: PKCS12

springdoc:
  api-docs:
    path: /api/company-events/api-docs
  swagger-ui:
    path: /api/company-events/swagger

telegram-bot:
  api-address: ${TELEGRAM_BOT_API_ADDRESS}